<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosRouterOs\Module'                        => __DIR__ . '/Module.php',
    'LosRouterOs\Controller\IndexController' => __DIR__ . '/src/LosRouterOs/Controller/IndexController.php',
    'LosRouterOsTest\Framework\TestCase'        => __DIR__ . '/tests/LosRouterOs/Framework/TestCase.php',
    'LosRouterOsTest\SampleTest'                => __DIR__ . '/tests/LosRouterOs/SampleTest.php',
);
