<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosRouterOs\Controller\IndexController'   => __DIR__ . '/src/LosRouterOs/Controller/IndexController.php',
    'LosRouterOs\Entity\Active'                => __DIR__ . '/src/LosRouterOs/Entity/Active.php',
    'LosRouterOs\Entity\Client'                => __DIR__ . '/src/LosRouterOs/Entity/Client.php',
    'LosRouterOs\Entity\ClientFactory'         => __DIR__ . '/src/LosRouterOs/Entity/ClientFactory.php',
    'LosRouterOs\Module'                       => __DIR__ . '/src/LosRouterOs/Module.php',
    'LosRouterOs\Options\ModuleOptions'        => __DIR__ . '/src/LosRouterOs/Options/ModuleOptions.php',
    'LosRouterOs\Options\ModuleOptionsFactory' => __DIR__ . '/src/LosRouterOs/Options/ModuleOptionsFactory.php',
    'LosRouterOs\Service\Router'               => __DIR__ . '/src/LosRouterOs/Service/Router.php',
);
